const questionsData = [
  { no: 1, q: "Astronomical unit (AU) is distance between Earth and Sun. 1 AU =", opts: ["1.496 x 10^8 km", "9.46 x 10^12 km", "3.084 x 10^13 km", "None"], ans: 0 },
  { no: 2, q: "Who discovered electron?", opts: ["Thomson", "Goldstein", "Rutherford", "Chadwick"], ans: 0 },
  { no: 3, q: "The magnitude of the sum of two vectors is equal to the difference of their magnitudes. What is the angle between the vectors?", opts: ["0°", "45°", "90°", "180°"], ans: 3 },
  { no: 4, q: "A particle is moving on a straight line path with constant acceleration directed along the direction of instantaneous velocity. Which statement is true?", opts: ["Particle may reverse the direction of motion.", "Distance covered = magnitude of displacement.", "Average velocity is less than average speed.", "Average velocity = instantaneous velocity."], ans: 1 },
  { no: 5, q: "A ball is projected from the top of a tower at an angle 60° with the vertical. What happens to the vertical component of its velocity?", opts: ["Increases continuously.", "Decreases continuously.", "Remains unchanged.", "First decreases and then increases."], ans: 3 },
  { no: 6, q: "A particle moving along a circular path due to a centripetal force having constant magnitude is an example of motion with:", opts: ["Constant speed and velocity.", "Variable speed and velocity.", "Variable speed and constant velocity.", "Constant speed and variable velocity."], ans: 3 },
  { no: 7, q: "A rod of mass M and length L is lying on a horizontal table. The work done in making it stand on one end will be:", opts: ["MgL", "MgL/2", "MgL/4", "2MgL"], ans: 1 },
  { no: 8, q: "A body weighs:", opts: ["Very slightly greater at night.", "Very slightly less at night.", "Exactly equal at day and night.", "Zero at night."], ans: 0 },
  { no: 9, q: "Two vessels have different base areas. They are filled with water to the same height. If the amount of water in one is 4 times that in the other, then the ratio of pressure on their bottoms will be:", opts: ["16:1", "8:1", "4:1", "1:1"], ans: 3 },
  { no: 10, q: "The speed of light in air is 3 x 10^8 m/s. What will be its speed in diamond whose refractive index is 2.4?", opts: ["3 x 10^8 m/s", "330 m/s", "1.25 x 10^8 m/s", "2.24 x 10^8 m/s"], ans: 2 },
  { no: 11, q: "Critical angle for water is:", opts: ["24°", "49°", "42°", "35°"], ans: 1 },
  { no: 12, q: "The pressure of H2 gas at a gas thermometer is 80 cm at 0°C and 110 cm at 100°C. At what temperature will it record 95 cm pressure?", opts: ["50°C", "75°C", "95°C", "150°C"], ans: 0 },
  { no: 13, q: "Heat required to raise the temperature of a body through 1°C is known as:", opts: ["Specific heat capacity", "Water equivalent", "Molar specification", "Thermal capacity"], ans: 0 },
  { no: 14, q: "The diameter of a wire is reduced to half. The resistance changes by factor:", opts: ["2", "4", "8", "16"], ans: 3 },
  { no: 15, q: "Which of the following is called the red planet?", opts: ["Venus", "Mercury", "Mars", "Jupiter"], ans: 2 },
  { no: 16, q: "The waste material present in an ore is called:", opts: ["Flux", "Alloy", "Gangue", "Slag"], ans: 2 },
  { no: 17, q: "Vapour density of a gas is 22. Its molecular weight will be:", opts: ["33", "22", "44", "11"], ans: 2 },
  { no: 18, q: "If 30 g of Mg and 30 g of O2 are reacted, then the residual mixture contains:", opts: ["40 g MgO + 20 g O2", "45 g MgO + 15 g O2", "50 g MgO + 10 g O2", "60 g MgO only"], ans: 2 },
  { no: 19, q: "Which of the following set of quantum numbers is not possible?", opts: ["n = 2, l = 1, m = 0, s = +1/2", "n = 2, l = 2, m = +1, s = -1/2", "n = 2, l = 1, m = -1, s = +1/2", "n = 2, l = 1, m = 0, s = -1/2"], ans: 1 },
  { no: 20, q: "Radioactivity was discovered by:", opts: ["Henry Becquerel", "Rutherford", "J.J. Thomson", "Madam Curie"], ans: 0 },
  { no: 21, q: "Which of the following expression at pressure represents Charles's law?", opts: ["V ∝ 1/T", "V ∝ 1/T^2", "V ∝ T", "V = d"], ans: 2 },
  { no: 22, q: "Solid CO2 is an example of:", opts: ["Ionic crystal", "Covalent crystal", "Metallic crystal", "Molecular crystal"], ans: 3 },
  { no: 23, q: "Which bond has maximum M.P. and B.P.?", opts: ["Ionic", "Covalent", "Co-ordinate covalent", "Hydrogen bond"], ans: 0 },
  { no: 24, q: "The atomic number of an element is 38. In which block does it lie?", opts: ["s-block", "p-block", "d-block", "f-block"], ans: 0 },
  { no: 25, q: "During fermentation of glucose the enzyme used is:", opts: ["Zymase", "Lipase", "Invertase", "Amylase"], ans: 0 },
  { no: 26, q: "What is the empirical formula of a hydrocarbon containing 75% carbon?", opts: ["C2H4", "CH4", "C3H9", "C2H6"], ans: 1 },
  { no: 27, q: "Example of amphoteric oxide is:", opts: ["SO2", "Na2O", "ZnO", "NO"], ans: 2 },
  { no: 28, q: "Colour pigments can be separated by:", opts: ["Filtration", "Distillation", "Chromatography", "Sublimation"], ans: 2 },
  { no: 29, q: "Which one is manufactured from sea weeds?", opts: ["F2", "I2", "Cl2", "Br"], ans: 1 },
  { no: 30, q: "Gas used in welding of iron or steel is:", opts: ["Methane", "Ethane", "Ethylene", "Acetylene"], ans: 3 },
  { no: 31, q: "A patient is generally advised to consume more meat, lentils, milk and egg in diet only when he/she suffers from:", opts: ["Rickets", "Kwashiorkor", "Anaemia", "Scurvy"], ans: 1 },
  { no: 32, q: "Tetanus disease is:", opts: ["Viral", "Bacterial", "Fungal", "None"], ans: 1 },
  { no: 33, q: "Kind of epithelium in inner lining of blood vessels?", opts: ["Cuboidal epithelium", "Columnar", "Ciliated columnar", "Squamous epithelium"], ans: 3 },
  { no: 34, q: "Which part of brain is involved in regulating body temperature?", opts: ["Medulla oblongata", "Cerebrum", "Cerebellum", "Hypothalamus"], ans: 3 },
  { no: 35, q: "The term antibiotic was coined by:", opts: ["Pasteur", "Edward Jenner", "Fleming", "Selman Waksman"], ans: 3 },
  { no: 36, q: "Which is not a feature of Annelida?", opts: ["Closed circulatory system", "Segmentation", "Pseudocoelom", "Ventral nerve cord"], ans: 2 },
  { no: 37, q: "Evolutionary history of organism is:", opts: ["Phylogeny", "Ancestry", "Paleontology", "Ontogeny"], ans: 0 },
  { no: 38, q: "HIV that causes AIDS first starts destroying:", opts: ["B-lymphocytes", "Platelets", "Leucocytes", "Helper T-cells"], ans: 3 },
  { no: 39, q: "Blood calcium level is lowered by deficiency of:", opts: ["Parathormone", "Calcitonin", "Thyroxine", "Both b and c"], ans: 0 },
  { no: 40, q: "First healthy mammal to be cloned is:", opts: ["Molly sheep", "Dolly sheep", "Polly sheep", "Monkey"], ans: 1 },
  { no: 41, q: "Ribosome can also be called:", opts: ["Microsome", "Oxyosome", "Dictyosome", "Ribonucleotide"], ans: 0 },
  { no: 42, q: "The first transgenic crop is:", opts: ["Tobacco", "Wheat", "Tomato", "Maize"], ans: 0 },
  { no: 43, q: "Tobacco mosaic virus is:", opts: ["Rod shaped", "Brick shaped", "Spherical", "None"], ans: 0 },
  { no: 44, q: "Bacterial DNA is identified as:", opts: ["DNA only", "DNA with histone", "DNA without histone", "DNA and RNA"], ans: 2 },
  { no: 45, q: "Which is sensitive to SO2 pollution?", opts: ["Lichens", "Algae", "Mosses", "Gymnosperms"], ans: 0 },
  { no: 46, q: "Cause of motility in male gamete is:", opts: ["Phototaxis", "Chemotaxis", "Thermotaxis", "Thermotropism"], ans: 1 },
  { no: 47, q: "Milk is purified by:", opts: ["Fermentation", "Pasteurisation", "Preservation", "Sterilisation"], ans: 1 },
  { no: 48, q: "Pollution can bring change in:", opts: ["Abiotic environment", "Biotic environment", "Both a and b", "Animals"], ans: 2 },
  { no: 49, q: "BOD is:", opts: ["Biological oxygen deficit", "Biosphere oxygen demand", "Biological oxygen demand", "None"], ans: 2 },
  { no: 50, q: "Which part of cinchona is used as a drug?", opts: ["Bark", "Leaf", "Pericarp", "Endosperm"], ans: 0 },

  { no: 81, q: "His pocket has been picked. It means:", opts: ["Picked his been his pocket.", "They have his pocket picked.", "Someone has picked his pocket.", "Picking has been done to his pocket."], ans: 2 },
  { no: 82, q: "More serious from the parent's point of view than the increasing expenditure on children's education is finding a good school. The more serious thing is:", opts: ["The parent's point of view", "Finding a good school", "Children's education", "Increasing education"], ans: 1 },
  { no: 83, q: "Here's my report ----- it at last.", opts: ["I finish", "I finished", "I've finished", "I'm finished"], ans: 2 },
  { no: 84, q: "Your parents are very upset with you and you are regretting over the wrongdoing.", opts: ["I wish they would understand me.", "I wish I could tell them the truth.", "I wish I hadn't disobeyed them.", "I wish they were happy."], ans: 2 },
  { no: 85, q: "He gave up ............", opts: ["Smoke", "To smoke", "Smoking", "To smoke"], ans: 2 },
  { no: 86, q: "The professor and psychologist......... come.", opts: ["Has", "Have", "Has", "Was"], ans: 0 },
  { no: 87, q: "Where's Robert? ........ a shower?", opts: ["Does he have", "Has he", "Has fiant", "Is he having"], ans: 3 },
  { no: 88, q: "An Englishman killed his mother for trying to save an Indian's life. The person trying to save the Indian's life..........", opts: ["Was an English woman", "Was saved", "Was killed", "Was an Indian"], ans: 2 },
  { no: 89, q: "I didn't smoke in the past but these days I'm used to.......", opts: ["Smoke", "Smokes", "Smoked", "Smoking"], ans: 3 },
  { no: 90, q: "Indirect speech of: She said, \"Good bye, my friend.\"", opts: ["She told her friends good bye.", "She bade good bye to her friends.", "She shouted good bye to her friends.", "She shouted good bye to her ends."], ans: 1 },
  { no: 91, q: "Fate smiles...... him in all his ventures.", opts: ["Upon", "At", "With", "For"], ans: 0 },
  { no: 92, q: "The downfall of this dictatorial regime is ...", opts: ["Imminent", "Eminent", "Urgent", "Optional"], ans: 0 },
  { no: 93, q: "Unexpected change in somebody's fortune is called:", opts: ["Vicissitude", "Verisimilitude", "Fortunate", "Catastrophe"], ans: 0 },
  { no: 94, q: "It's time to take tea. It means .............", opts: ["Tea should be taken.", "Tea is to be taken.", "It's time for tea to be taken.", "Tea should be taken now."], ans: 2 },
  { no: 95, q: "When I looked round the door, the baby ......... quietly.", opts: ["Is sleeping", "Slept", "Was sleeping", "Were sleeping"], ans: 2 },
  { no: 96, q: "......... a party next Friday. We've sent out the invitations.", opts: ["We had", "We have", "We'll have", "We are having"], ans: 3 },
  { no: 97, q: "By 2020, I..... Bachelor's in science.", opts: ["Complete", "Am completing", "Will complete", "Will have completed"], ans: 3 },
  { no: 98, q: "Julia was out of breath because .........", opts: ["She had been running", "She did run", "She's been running", "She's run"], ans: 0 },
  { no: 99, q: "This house is ... of the two.", opts: ["The best", "The better that", "The better", "Better"], ans: 3 },
  { no: 100, q: "At this time tomorrow....... over the Pacific Ocean.", opts: ["We flying", "We'll fly", "We'll be flying", "We to fly"], ans: 2 }
];
