const questionsData = [
    { q: "Which of the following is a vector quantity?", opts: ["Force", "Acceleration", "Momentum", "All of the above"], ans: 3 },
    { q: "If a body is freely falling on the surface of earth, then the acceleration is:", opts: ["positive", "negative", "zero", "none of the above"], ans: 0 },
    { q: "What is the wave length of red light?", opts: ["4000Å", "7000Å", "7000 mm", "700 cm"], ans: 1 },
    { q: "The efficiency of filament bulb is:", opts: ["20%", "30%", "70%", "10%"], ans: 3 },
    { q: "In which of the following medium, the velocity of sound is maximum?", opts: ["Air", "Vacuum", "Water", "Glass"], ans: 3 },
    { q: "If water is cooled from 4°C to below, the volume of water:", opts: ["increases", "decreases", "remains constant", "none"], ans: 0 },
    { q: "The resistance of a wire increases with _______ of the wire.", opts: ["increasing length", "decreasing cross section area", "both of above", "none of above"], ans: 2 },
    { q: "Which of the following has minimum refractive index?", opts: ["Glass", "Diamond", "Water", "Air"], ans: 3 },
    { q: "A bus of mass 1000 Kg is moving with velocity 25 m/s. What is the amount of force required to stop the bus in 5 sec?", opts: ["2000N", "4000N", "5000N", "3000N"], ans: 2 },
    { q: "Velocity of sound _______ with increase in density of medium.", opts: ["increases", "decreases", "remains same", "none of above"], ans: 0 },
    { q: "Which of the following is the smallest unit of length?", opts: ["millimeter", "micrometer", "nanometer", "angstrom unit"], ans: 3 },
    { q: "Which of the following elements does not belong to alkali metals?", opts: ["Na", "Li", "Mg", "K"], ans: 2 },
    { q: "Methyl orange gives ____ colour with base.", opts: ["red", "pink", "orange", "yellow"], ans: 3 },
    { q: "Which of the following is common alcohol (wine)?", opts: ["methyl alcohol", "ethyl alcohol", "propyl alcohol", "butyl alcohol"], ans: 1 },
    { q: "Cobalt oxide is added to ordinary glass to make _______ glass.", opts: ["black", "red", "hard", "blue"], ans: 3 },
    { q: "What should be the amount of sugar to make saturated solution of sugar in 500gm water at 25°C, if solubility of sugar at that temp. is 20.", opts: ["20", "25", "100", "200"], ans: 2 },
    { q: "The element with atomic no. 24 is:", opts: ["Iron", "Cadmium", "Chromium", "Copper"], ans: 2 },
    { q: "What is the molecular formula for bleaching powder?", opts: ["CaCl2", "CaOCl2", "CuSO4", "MgCl2"], ans: 1 },
    { q: "Glycerol is an example of _______.", opts: ["monohydric alcohol", "dihydric alcohol", "trihydric alcohol", "aldehyde"], ans: 2 },
    { q: "Which of the following metal has highest boiling point?", opts: ["Aluminium", "Silver", "Copper", "Gold"], ans: 2 },
    { q: "Amphibian of plant kingdom is:", opts: ["Algae", "Fungi", "Gymnosperm", "Bryophyta"], ans: 3 },
    { q: "The largest animal cell is _______.", opts: ["Ostrich egg", "RBC", "WBC", "Neuron"], ans: 0 },
    { q: "Nucleolus is present in _______.", opts: ["cytoplasm", "nucleoplasm", "cell membrane", "plastid"], ans: 1 },
    { q: "Which of the following planet spins most slowly?", opts: ["Venus", "Earth", "Mars", "Jupiter"], ans: 0 },
    { q: "Which of the following does not belong to phylum coelenterata?", opts: ["Hydra", "Volvox", "Obelia", "both b and c"], ans: 1 },
    { q: "The animal in which both male and female sex organ are present in a single individual is called:", opts: ["sexual", "asexual", "hermaphrodite", "monosexual"], ans: 2 },
    { q: "The scientific name of 'pea' is:", opts: ["Allium sativum", "Rosa indica", "Pisum sativum", "Magnifera indica"], ans: 2 },
    { q: "Crossing over starts in _______.", opts: ["Diplotene", "Zygotene", "Leptotene", "Pachytene"], ans: 3 },
    { q: "What is the gametophyte of fern plant?", opts: ["Thallus", "Inducicum", "Flowers", "Prothallus"], ans: 3 },
    { q: "Bloods are made with _______ tissues.", opts: ["epithelial", "connective", "muscular", "nervous"], ans: 1 },
    { q: "Heart is a muscular organ made of _______ muscles.", opts: ["voluntary", "cardiac", "involuntary", "skeletal"], ans: 1 },
    { q: "Which one of these is not an appropriate method of waste disposal?", opts: ["sanitary landfill", "incineration", "dumping", "piling up at road side"], ans: 3 },
    { q: "Which one of these is caused by an organism called 'Bordetella Pertusis'?", opts: ["tetanus", "whooping cough", "diphtheria", "poliomyelitis"], ans: 1 },
    { q: "One of the objectives of first aid treatment is to _______.", opts: ["save the life of an injured person", "cure a patient", "both of the above", "none of above"], ans: 2 },
    { q: "Function of vitamin 'K' is to _______.", opts: ["improve vision", "blood clotting", "increase blood cell", "improve muscles"], ans: 1 },
    { q: "What is the percentage of water of a normal body weight?", opts: ["60-70", "75-80", "80-90", "85-95"], ans: 0 },
    { q: "Which one of these is not communicable disease?", opts: ["TB", "Common cold", "Cancer", "Cholera"], ans: 2 },
    { q: "_______ is not a nutrient.", opts: ["Protein", "Medicine", "Vitamin", "Minerals"], ans: 1 },
    { q: "Safe motherhood is not affected by _____.", opts: ["age", "smoking", "whether", "food intake"], ans: 2 },
    { q: "DPT is vaccinated to a child _______ times.", opts: ["1", "2", "3", "4"], ans: 2 },
    { q: "Norplant is a _______.", opts: ["pills", "permanent method of family planning", "Depo-Provera injection", "temporary method of family planning implanted in a mid arm of a woman"], ans: 3 },
    { q: "Most of the disease of a community in Nepal can be controlled by _______.", opts: ["improving community environment", "providing clean drinking water", "raising the income level", "providing health services"], ans: 0 },
    { q: "Goiter occurs due to the deficiency of ____.", opts: ["iron", "vitamin", "calcium", "iodine"], ans: 3 },
    { q: "Full form of AIDS is _______.", opts: ["Acute Immune Deficiency Syndrome", "Acquired Immuno Deficiency Syndrome", "Acquired Immune Deficient Syndrome", "Acquired Immune Deficiency Symptoms"], ans: 1 },
    { q: "Syphilis is caused by _______.", opts: ["Treponema pallidum", "Brodetlla pertusis", "Entamoeba hystolytica", "Corynebacterium diphtheria"], ans: 0 },
    { q: "The most appropriate age group to become pregnancy for a woman is _______.", opts: ["15-20 years", "20-25 years", "25-35 years", "35-40 years"], ans: 1 },
    { q: "Which of these is not a female reproductive organ?", opts: ["uterus", "fallopian tube", "scrotum", "cervix"], ans: 2 },
    { q: "Family health is not affected by _______.", opts: ["literacy", "household size", "cultural environment", "geographic environment"], ans: 3 },
    { q: "Which of these is not a micro-organism?", opts: ["virus", "cell", "bacteria", "fungus"], ans: 1 },
    { q: "Nepali people need _______ caloric food on an average a day.", opts: ["2000", "2250", "2500", "2750"], ans: 1 },
    { q: "Human body has _______ pieces of bones.", opts: ["204", "206", "208", "210"], ans: 1 },
    { q: "Cause of population change is _______.", opts: ["birth rate", "immigration", "death rate", "all of above"], ans: 3 },
    { q: "Purification of milk is called _______.", opts: ["sterilization", "pasteurization", "distillation", "filtration"], ans: 1 },
    { q: "Child mortality rate in Nepal is high due to _______.", opts: ["fever", "acute respiratory infection", "tetanus", "all of the above"], ans: 3 },
    { q: "Which of these is not a viral disease?", opts: ["poliomyelitis", "measles", "leprosy", "hepatitis"], ans: 2 },
    { q: "Suman speaks ______ English.", opts: ["fluent", "fluently", "fluency", "flowing"], ans: 0 },
    { q: "He is sitting ____ the table ____ the bench.", opts: ["on, on", "at, on", "at, at", "on, at"], ans: 1 },
    { q: "She is junior ______ me.", opts: ["to", "than", "with", "by"], ans: 0 },
    { q: "They ______ him to cut wood.", opts: ["got", "made", "had", "make"], ans: 0 },
    { q: "The letter was written ______ red ink.", opts: ["in", "with", "on", "by"], ans: 0 },
    { q: "The teacher said to me, \"You can do if you try\".", opts: ["The teacher told me that she could do if I tried.", "The teacher told me that I could do if I tried.", "The teacher told me that you can do if you try.", "The teacher told me that I can do if I try."], ans: 1 },
    { q: "Their _______ based on facts.", opts: ["information is", "informations are", "information are", "informations is"], ans: 0 },
    { q: "You'd better _______ a doctor.", opts: ["seen", "to see", "see", "seeing"], ans: 2 },
    { q: "I have been teaching English ______ 1999.", opts: ["for", "since", "from", "to"], ans: 1 },
    { q: "The correct spelling is _______.", opts: ["karnel", "colonel", "colonell", "kornel"], ans: 1 },
    { q: "She does not _______ money.", opts: ["has", "have", "had", "gets"], ans: 1 },
    { q: "One of the girls _______ gone out.", opts: ["have", "are", "has", "is"], ans: 2 },
    { q: "The hotter it is, _______ I feel.", opts: ["more miserable", "the more miserable", "the much miserable", "the most miserable"], ans: 1 },
    { q: "Antonym of brave is:", opts: ["coward", "army officer", "greedy", "policeman"], ans: 0 },
    { q: "I am _______ to take revenge.", opts: ["good enough", "enough good", "experienced good", "enough better"], ans: 0 },
    { q: "Had I born in the USA, I _______ a car.", opts: ["had purchased", "will have purchased", "would purchase", "would have purchased"], ans: 3 },
    { q: "He was not _______ Indian.", opts: ["a", "an", "the", "no article"], ans: 1 },
    { q: "Let us go home, _______?", opts: ["shall we", "will we", "will you", "shall I"], ans: 2 },
    { q: "I am used to _______ late night.", opts: ["read", "reading", "reads", "red"], ans: 1 },
    { q: "She is _______ NCC officer.", opts: ["a", "the", "no article", "an"], ans: 3 },
    { q: "The driver is good _______ driving.", opts: ["at", "in", "for", "on"], ans: 0 },
    { q: "She had never _______ by an insect.", opts: ["been stung", "been stunged", "was stung", "been stunged"], ans: 0 },
    { q: "I saw him _______.", opts: ["played", "had played", "play", "to play"], ans: 2 },
    { q: "You will pass the final exam _______ you study hard.", opts: ["because of", "so that", "provided that", "as though"], ans: 2 },
    { q: "In 2020, she ______ in the same school.", opts: ["will be working", "will work", "will have worked", "will be work"], ans: 0 }
];
